services:
  app:
    image: management-abadicomm:staging
    container_name: management-abadicomm-staging
    build:
      context: . 
      dockerfile: DockerfileStaging
    restart: unless-stopped
    ports:
      - "127.0.0.1:9002:9000"
    volumes:
      - ./storage:/app/storage:rw
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Access host PostgreSQL